### PR TITLE
Myfirst module

### PR DESCRIPTION
**Pull request by wolterbwambale**
this is my first module

### CODE REVIEW

**Review by divinecharlotte — CHANGES_REQUESTED** [review]
Hi @wolterbwambale 👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!


### To Highlight 🎯 💡 

1. Good commit messages
2. Linters are passing

## Required Changes ♻️
☠️ I can see you deleted the previous branches where you had previous reviews which is not good kindly  next time do not create new PR for the project you've got already some previous reviews, this will help reviewers to not get confused
- [ ] kindly consider editing the provided Microverse  Readme template to come up with a Readme related to your project this will  make  your readme brief  please check the following:

- consider editing this "Microverse README Template" to something like this "Hello Microverse project " to make your readme title more descriptive
-  consider removing these brackets on the title " [Hello world]"  and removing this "[Hello world] is a..." in its body this will make this section  look better
- consider editing your  tech stack section so that it will contain only the stack used n this project this will prevent confusion for people who might visit this project
- kindly remove the live demo section as you are not deploying this project to avoid confusion from visitors to your project this will help your readme look more professional
- kindly add more information to your getting started section to make it more descriptive
- consider removing the second author as you are the only person who worked on this project and put into consideration adding your social media really links
- kindly consider adding more information in your Pr description to let people know what you did in the current branch
- Finally, consider adding a working link to your MIT license

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wolterbwambale** [comment]
@divinecharlotte 
updated the README file

**Review by GedeonTS — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED :recycle: :
Hi @wolterbwambale  , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights :tophat: :+1: 
- No linter errors :+1: 
- Good use of GitHub flow :+1: 

 ## Required Changes ♻️
- [ ] As requested by the previous reviewer [here](https://github.com/wolterbwambale/Hello-world/pull/1#:~:text=kindly%20remove%20the,your%20MIT%20license), kindly consider doing the following:
 - kindly remove the live demo section as this project is not going to be deployed 

 - kindly add  information to your getting started section to make it more descriptive and professional

 - consider removing the second author as you are the only person who worked on this project and put into consideration adding your social media really links

 - kindly consider adding more information in your Pr description to let people know what you did in the current branch(tell them that you added test.md to .gitignore, created halt/css files, and so on)

- You have done well creating MIT.md, however, the link in README is still not working, kindly check it out(I think if you changed the link to go to MIT.md instead of LICENSE it will work
_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wolterbwambale** [comment]
@GedeonTS I have updated the README file and attached the license.

**Review by roshan-bajgain — APPROVED** [review]
Hi @wolterbwambale, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions
- [ ] I would suggest you please write more summary on your pull request and title must be descriptive. Please keep in mind from next time.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
